export const Actiontypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SET_CART_PRODUCTS: "SET_CART_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};

export default Actiontypes;
